/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'advornikov' at '09.02.17 11:48' with Gradle 2.14.1
 *
 * @author advornikov, @date 09.02.17 11:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
